[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "interest"
description = "A package to extract hystorical news sentiments"
authors = [
    {name = "Shiva Nadi", email = "s.nadi@uu.nl"},
    {name = "Parisa Zahedi", email = "p.zahedi@uu.nl"},
    {name = "Matty Vermet", email = "m.s.vermet@uu.nl"}
]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version"]

dependencies = ["tqdm","pandas","pandas-stubs", "types-tqdm","spacy","scikit-learn","numpy","scipy"
]

[project.optional-dependencies]
lint = ["flake8"]
test = ["pytest", "mypy"]

[tool.setuptools]
packages = ["interest"]

[tool.flake8]
max-line-length = 99

[tool.pylint.'FORMAT']
max-line-length=100
max-locals=35
max-args=10

[[tool.mypy.overrides]]
module = [
    "scipy.*",
    "pandas.*",
    "sklearn.*"
]
ignore_missing_imports = true
